In [5]:
#NumPy

In [6]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np

In [8]:
#Creating Arrays

In [9]:
sample_array = np.array([1,2,3,4])

In [10]:
sample_array

array([1, 2, 3, 4])

In [11]:
sample_array2 = np.array([6,7,6,9,8,3])

In [12]:
sample_array2

array([6, 7, 6, 9, 8, 3])

In [13]:
# 2D Array( a Matrix) with two rows and two coloumns

In [14]:
sample_array_2 = np.array([[1,2],[3,4]])

In [15]:
sample_array_2

array([[1, 2],
       [3, 4]])

In [16]:
demo_array = np.array([[38,87],[67,92]])

In [17]:
demo_array

array([[38, 87],
       [67, 92]])

In [18]:
# 3D Tensor ( 2 matrices ,each with 2 rows and 2 coloumns)

In [19]:
sample_tensor_3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [20]:
sample_tensor_3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [21]:
sample_tensor_3 = np.array([[[35,36],[64,38]],[[98,23],[79,48]]])

In [22]:
sample_tensor_3

array([[[35, 36],
        [64, 38]],

       [[98, 23],
        [79, 48]]])

In [23]:
# 0-D Array (scaler) 5
# 1-D Array (vector) [1,2,3,4]
# 2-D Array (Matrix) (rows,coloumns)
# 3-D Array  (Tensor)  (page,row,column)

In [24]:
# Array Properties 

In [25]:
sample_array = np.array([[1,2,3],[4,5,6]])

In [26]:
sample_array

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
# Shape

In [28]:
sample_array.shape          # calculates dimensions

(2, 3)

In [29]:
sample_array.ndim

2

In [30]:
# Total elements

In [31]:
sample_array.size

6

In [32]:
# data type

In [33]:
sample_array.dtype

dtype('int64')

In [34]:
sample_array = np.array([[[1,2],[3,5]],[[2,8],[9,5]]])

In [35]:
sample_array.dtype

dtype('int64')

In [36]:
sample_array.size

8

In [37]:
sample_array.ndim

3

In [38]:
sample_array.shape

(2, 2, 2)

In [39]:
# special arrays

In [40]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [42]:
np.arange(0,10,2)          # (start , stop , step)

array([0, 2, 4, 6, 8])

In [43]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [44]:
np.arange(100,0,10)

array([], dtype=int64)

In [45]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [46]:
# Indexing and slicing

In [47]:
sample_array = np.array([10,20,30,40])

In [48]:
sample_array

array([10, 20, 30, 40])

In [49]:
sample_array[0]

np.int64(10)

In [50]:
sample_array[2]

np.int64(30)

In [51]:
sample_array[-1]

np.int64(40)

In [52]:

# slicing

In [53]:
sample_array[1:3]

array([20, 30])

In [54]:
sample_array[0:4:2]

array([10, 30])

In [55]:
a = np.array([1,2,3])

In [56]:
b = np.array([4,5,6])

In [57]:
a

array([1, 2, 3])

In [58]:
b

array([4, 5, 6])

In [59]:
a + b

array([5, 7, 9])

In [60]:
a - b

array([-3, -3, -3])

In [61]:
a * b

array([ 4, 10, 18])

In [62]:
a / b

array([0.25, 0.4 , 0.5 ])

In [63]:
c = np.array([9,8,3])

In [64]:
d = np.array([8,9,4])

In [65]:
c

array([9, 8, 3])

In [66]:
d

array([8, 9, 4])

In [67]:
c + d

array([17, 17,  7])

In [68]:
c - d

array([ 1, -1, -1])

In [69]:
c * d

array([72, 72, 12])

In [70]:
c / d

array([1.125     , 0.88888889, 0.75      ])

In [71]:
# Mathematical functions

In [72]:
sample_array = np.array([1,4,9])

In [73]:
sample_array

array([1, 4, 9])

In [74]:
np.sqrt(sample_array)

array([1., 2., 3.])

In [75]:
sample_array1 = np.array([16,81,100])

In [76]:
sample_array1

array([ 16,  81, 100])

In [77]:
np.sqrt(sample_array1)

array([ 4.,  9., 10.])

In [78]:
np.exp(sample_array)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03])

In [79]:
sample_array = np.array([1,4,9])

In [80]:
sample_array

array([1, 4, 9])

In [81]:
np.exp(sample_array)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03])

In [82]:
np.log(sample_array)

array([0.        , 1.38629436, 2.19722458])

In [83]:
np.log(sample_array1)

array([2.77258872, 4.39444915, 4.60517019])

In [84]:
# stastistical func

In [85]:
sample_array = np.array([1,2,3,4,5])

In [86]:
sample_array

array([1, 2, 3, 4, 5])

In [87]:
np.mean(sample_array)

np.float64(3.0)

In [88]:
np.median(sample_array)

np.float64(3.0)

In [89]:
np.std(sample_array)

np.float64(1.4142135623730951)

In [90]:
np.min(sample_array)

np.int64(1)

In [91]:
np.max(sample_array)

np.int64(5)

In [92]:
# Reshaping arrays

In [93]:
sample_array = np.arange(0,6)

In [94]:
sample_array

array([0, 1, 2, 3, 4, 5])

In [95]:
reshaped = sample_array.reshape(2,3)

In [96]:
reshaped

array([[0, 1, 2],
       [3, 4, 5]])

In [97]:
# Array Flattening

In [98]:
sample_array = np.array([[1,2],[3,4]])

In [99]:
sample_array

array([[1, 2],
       [3, 4]])

In [100]:
sample_array.flatten()

array([1, 2, 3, 4])

In [101]:
sample_array = np.array([[[1,2],[3,5]],[[2,8],[9,5]]])

In [102]:
sample_array

array([[[1, 2],
        [3, 5]],

       [[2, 8],
        [9, 5]]])

In [103]:
sample_array.flatten()

array([1, 2, 3, 5, 2, 8, 9, 5])

In [104]:
# Joining Arrays

In [105]:
a = np.array([1,2,3,4])

In [106]:
b= np.array([5,6,7,8])

In [107]:
a

array([1, 2, 3, 4])

In [108]:
b

array([5, 6, 7, 8])

In [109]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [110]:
np.concat((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [111]:
# Spliting Arrays

In [112]:
sample_array = np.array([1,2,3,4])

In [113]:
sample_array


array([1, 2, 3, 4])

In [114]:
np.array_split(sample_array,2)

[array([1, 2]), array([3, 4])]

In [115]:
# Random module

In [116]:
np.random.rand(3)

array([0.92351126, 0.89120684, 0.41326666])

In [118]:
np.random.randint(1,10,5)        # (between 1 to 10 and any 5 numbers)

array([3, 7, 2, 6, 6], dtype=int32)

In [119]:
# Axis Concept

In [121]:
sample_array = np.array([[1,2],[3,4]])

In [122]:
sample_array

array([[1, 2],
       [3, 4]])

In [125]:
np.sum(sample_array,axis=0)       # columnwise addition when 0

array([4, 6])

In [126]:
np.sum(sample_array,axis=1)      # rowwise addition when 1

array([3, 7])